### ISSUE TITLE
aggiornamento codice

### ISSUE THREAD

**Issue by Misael-Micciche-JCMaxwell-5Ai** [Veronica-De-Santis-JCMaxwell-5Ai/Java-Sockets#5]
Ciao veronica,
hai gia aggiunto la parte che permette di far comunicare due client?

**Comment by Veronica-De-Santis-JCMaxwell-5Ai** [comment]
Ciao, non l'ho ancora aggiunta. Organiziamoci per vederci e farlo insieme!
