### ISSUE TITLE
Problema client

### ISSUE THREAD

**Issue by Misael-Micciche-JCMaxwell-5Ai** [Veronica-De-Santis-JCMaxwell-5Ai/Java-Sockets#6]
Ciao veronica,
Ho notato un problema testando il codice. Quando un client si disconnette, il suo nikname non viene cancellato dalla lista

**Comment by Veronica-De-Santis-JCMaxwell-5Ai** [comment]
Corretto alla linea 86 della classe "SocketWorker.java"
