### ISSUE TITLE
Correzione Bug

### ISSUE THREAD

**Issue by Misael-Micciche-JCMaxwell-5Ai** [Veronica-De-Santis-JCMaxwell-5Ai/Java-Sockets#8]
Mancano la dichiarazione delle librerie per usare la lista nella classe principale ('ServerTestoMultiThreaded') e una parentesi alla linea 74 della classe 'socketWorker'

**Comment by Veronica-De-Santis-JCMaxwell-5Ai** [comment]
Corretti thanks! ;)
